### PR TITLE
Fix #352 Returns error when passing pointer to RegisterStructValidation

### LINKED ISSUE #352: RegisterStructValidation does not work on pointer types
### Package version eg. v8, v9: 

`v8.18.2`

### Issue, Question or Enhancement:

Issue

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"reflect"

	validator "gopkg.in/go-playground/validator.v8"
)

type User struct {
	FirstName string `json:"fname"`
	LastName  string `json:"lname"`
	Email     string `binding:"required,email"`
}

func UserStructLevelValidation(v *validator.Validate, structLevel *validator.StructLevel) {
	user := structLevel.CurrentStruct.Interface().(*User)

	if len(user.FirstName) == 0 && len(user.LastName) == 0 {
		structLevel.ReportError(
			reflect.ValueOf(user.FirstName), "FirstName", "fname", "fnameorlname",
		)
		structLevel.ReportError(
			reflect.ValueOf(user.LastName), "LastName", "lname", "fnameorlname",
		)
	}
}

func main() {
	v := validator.New(&validator.Config{TagName: "validate"})
	v.RegisterStructValidation(UserStructLevelValidation, &User{})

	user := &User{Email: "Badger.Smith@gmail.com"}

	if errs := v.Struct(user); errs != nil {
		fmt.Println(errs)
	} else {
		fmt.Println("struct validation failed")
	}
}
```

This does not call the struct validation function. If this is known behavior and has been documented somewhere, I apologise.

### PR DESCRIPTION
**Pull request by suekto-andreas**
Fixes #352.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] Tests exist or have been written that cover this particular change.

Change Details:
- Returns error on pointer type detection at RegisterStructValidationCtx
- Returns error at RegisterStructValidation

@go-playground/admins

### CODE REVIEW

File: validator_instance.go [hunk 1]
```diff
@@ -189,26 +189,38 @@ func (v *Validate) RegisterAlias(alias, tags string) {
...
 // - this method is not thread-safe it is intended that these all be registered prior to any validation
-func (v *Validate) RegisterStructValidationCtx(fn StructLevelFuncCtx, types ...interface{}) {
+func (v *Validate) RegisterStructValidationCtx(fn StructLevelFuncCtx, types ...interface{}) error {
 
 	if v.structLevelFuncs == nil {
 		v.structLevelFuncs = make(map[reflect.Type]StructLevelFuncCtx)
 	}
 
+	for _, t := range types {
+		if reflect.ValueOf(t).Kind() == reflect.Ptr {
```
Comment (joeybloggs) [inline validator_instance.go]: Have you tried using [Elem](https://golang.org/pkg/reflect/#Value.Elem) or [Indirect](https://golang.org/pkg/reflect/#Indirect) to automatically downgrade instead of returning an error?

Comment (suekto-andreas) [reply validator_instance.go]: Thanks @joeybloggs, pushed a commit using Indirect to downgrade it
